/**
 * React项目生成器
 * 将schema转换为完整的React项目
 */

import { ComponentSchema } from '@/types';
import JSZip from 'jszip';
import { saveAs } from 'file-saver';

export interface ProjectConfig {
    name: string;
    version?: string;
    description?: string;
    author?: string;
}

export class ProjectGenerator {
    /**
     * 生成React项目
     */
    async generateProject(schema: ComponentSchema, config: ProjectConfig): Promise<void> {
        const zip = new JSZip();
        const projectName = config.name || 'my-lowcode-app';

        // 生成项目文件
        this.generatePackageJson(zip, config);
        this.generateViteConfig(zip);
        this.generateIndexHtml(zip, config);
        this.generateGitignore(zip);
        this.generateReadme(zip, config);

        // 生成源代码
        this.generateMainJsx(zip);
        this.generateAppJsx(zip, schema);
        this.generateAppCss(zip);
        this.generateIndexCss(zip);
        this.generateComponents(zip, schema);

        // 生成并下载zip
        const blob = await zip.generateAsync({ type: 'blob' });
        saveAs(blob, `${projectName}.zip`);
    }

    /**
     * 生成package.json
     */
    private generatePackageJson(zip: JSZip, config: ProjectConfig) {
        const packageJson = {
            name: config.name || 'my-lowcode-app',
            private: true,
            version: config.version || '0.1.0',
            type: 'module',
            description: config.description || 'Generated by Lowcode Engine',
            author: config.author || '',
            scripts: {
                dev: 'vite',
                build: 'vite build',
                preview: 'vite preview'
            },
            dependencies: {
                react: '^18.2.0',
                'react-dom': '^18.2.0',
                antd: '^5.12.0'
            },
            devDependencies: {
                '@vitejs/plugin-react': '^4.2.1',
                vite: '^5.0.8'
            }
        };

        zip.file('package.json', JSON.stringify(packageJson, null, 2));
    }

    /**
     * 生成vite.config.js
     */
    private generateViteConfig(zip: JSZip) {
        const viteConfig = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    open: true
  }
})
`;
        zip.file('vite.config.js', viteConfig);
    }

    /**
     * 生成index.html
     */
    private generateIndexHtml(zip: JSZip, config: ProjectConfig) {
        const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${config.name || 'My Lowcode App'}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;
        zip.file('index.html', html);
    }

    /**
     * 生成.gitignore
     */
    private generateGitignore(zip: JSZip) {
        const gitignore = `# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?
`;
        zip.file('.gitignore', gitignore);
    }

    /**
     * 生成README.md
     */
    private generateReadme(zip: JSZip, config: ProjectConfig) {
        const readme = `# ${config.name || 'My Lowcode App'}

${config.description || 'This project was generated by Lowcode Engine.'}

## 快速开始

### 安装依赖
\`\`\`bash
npm install
\`\`\`

### 启动开发服务器
\`\`\`bash
npm run dev
\`\`\`

### 构建生产版本
\`\`\`bash
npm run build
\`\`\`

### 预览生产构建
\`\`\`bash
npm run preview
\`\`\`

## 技术栈

- React 18
- Vite
- Ant Design

## 作者

${config.author || 'Generated by Lowcode Engine'}
`;
        zip.file('README.md', readme);
    }

    /**
     * 生成main.jsx
     */
    private generateMainJsx(zip: JSZip) {
        const mainJsx = `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
`;
        zip.file('src/main.jsx', mainJsx);
    }

    /**
     * 生成App.jsx
     */
    private generateAppJsx(zip: JSZip, schema: ComponentSchema) {
        const appCode = this.schemaToReactCode(schema);
        const appJsx = `import React from 'react'
import './App.css'

function App() {
  return (
    <div className="App">
${this.indentCode(appCode, 6)}
    </div>
  )
}

export default App
`;
        zip.file('src/App.jsx', appJsx);
    }

    /**
     * 生成App.css
     */
    private generateAppCss(zip: JSZip) {
        const appCss = `.App {
  min-height: 100vh;
  padding: 20px;
}
`;
        zip.file('src/App.css', appCss);
    }

    /**
     * 生成index.css
     */
    private generateIndexCss(zip: JSZip) {
        const indexCss = `:root {
  font-family: Inter, system-ui, Avenir, Helvetica, Arial, sans-serif;
  line-height: 1.5;
  font-weight: 400;

  color-scheme: light dark;
  color: rgba(255, 255, 255, 0.87);
  background-color: #242424;

  font-synthesis: none;
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

* {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  margin: 0;
  display: flex;
  place-items: center;
  min-width: 320px;
  min-height: 100vh;
}

#root {
  width: 100%;
}
`;
        zip.file('src/index.css', indexCss);
    }

    /**
     * 生成组件文件
     */
    private generateComponents(zip: JSZip, schema: ComponentSchema) {
        // 这里可以扩展，为复杂组件生成单独的文件
        // 目前简化处理，所有代码都在App.jsx中
    }

    /**
     * Schema转React代码
     */
    private schemaToReactCode(schema: ComponentSchema, depth: number = 0): string {
        const indent = '  '.repeat(depth);
        const { componentName, props = {}, children = [] } = schema;

        // 处理props
        const propsStr = Object.entries(props)
            .map(([key, value]) => {
                if (typeof value === 'string') {
                    return `${key}="${value}"`;
                } else if (typeof value === 'boolean') {
                    return value ? key : '';
                } else if (typeof value === 'number') {
                    return `${key}={${value}}`;
                } else {
                    return `${key}={${JSON.stringify(value)}}`;
                }
            })
            .filter(Boolean)
            .join(' ');

        const openTag = propsStr ? `<${componentName} ${propsStr}` : `<${componentName}`;

        // 如果有子节点
        if (children.length > 0) {
            const childrenCode = children
                .map(child => this.schemaToReactCode(child, depth + 1))
                .join('\n');

            return `${indent}${openTag}>\n${childrenCode}\n${indent}</${componentName}>`;
        } else {
            return `${indent}${openTag} />`;
        }
    }

    /**
     * 代码缩进
     */
    private indentCode(code: string, spaces: number): string {
        const indent = ' '.repeat(spaces);
        return code.split('\n').map(line => indent + line).join('\n');
    }
}

// 导出单例
export const projectGenerator = new ProjectGenerator();
